version: "2"
volumes:
  flow-data:
  log-data:


services:
  node-red-pigpiod:
    build: ./node-red-pigpiod
    restart: unless-stopped
    privileged: true
    ports:
      - 8888:8888
    expose:
     - 8888
    depends_on:
     - logspooler

  node-red:
    build: ./node-red
    volumes:
      - 'flow-data:/data'
    restart: unless-stopped
    ports:
      - 1880:1880
    expose:
     - 1880
    depends_on:
     - node-red-pigpiod
     - logspooler

  logagent: 
    image: 'sematext/logagent:latest' 
    environment: 
      - LOGS_TOKEN=cf83a774-846f-4de1-8367-2c2722d7a8a4
      - REGION=US 
      - LOG_GLOB=/data/logs/node.log
    cap_add: 
      - SYS_ADMIN  
    restart: always 
    volumes: 
      - 'log-data:/data/logs' 

  logspooler: 
    build: ./logspooler 
    environment: 
      - LOG_GLOB=/data/logs/node.log
    restart: always 
    depends_on:
     - logagent
    volumes: 
      - 'log-data:/data/logs' 
    labels:
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
      io.balena.features.balena-socket: '1'
