version: "2"
volumes:
  flow-data:

services:
  node-red-pigpiod:
    build: ./node-red-pigpiod
    restart: unless-stopped
    privileged: true
    ports:
      - 8888:8888
    expose:
     - 8888

  node-red:
    build: ./node-red
    volumes:
      - 'flow-data:/data'
    restart: unless-stopped
    ports:
      - 1880:1880
    expose:
     - 1880
    depends_on:
     - node-red-pigpiod
